---
title: "Ungereimtheiten"
output: html_notebook
---

### 1. Fehlende Baumarten

Okay, wir haben 24 Bäume ohne Baumart. Die hau ich weg.

```{r, rows.print=15}
source(file = "SCRIPT/IBF/LOAD_NV.R") 
#  Loads and cleans all data from the Winter IBF surveys
dfn <- data_nv[data_nv$Flaeche=="Schotten",]
library(dplyr)
dfn %>% 
	count(Baumart_lang)
```

------------------------------------------------------------------------

### 2. Astralbäume

Auch sind **nach der Bereinugung** in den Daten 17 Eschen, die keinen Wert bei *Anzahl.Triebe* haben.

```{r, rows.print=15}
dfn <- dfn[!is.na(dfn$Baumart_kurz),] # Löschung der 24 Einträge ohne Baumart
	dfn[dfn$Baumart_kurz=="GEs",] %>% 
	count(Anzahl.Triebe)
```

Hier als Subset:\

```{r, rows.print=17}
dfn <- dfn[!is.na(dfn$Baumart_kurz),] # Löschung der 24 Einträge ohne Baumart
DT::datatable(
	subset(dfn, is.na(dfn$Anzahl.Triebe) & dfn$Baumart_kurz=="GEs")[,c(1,4, 13, 15, 16, 17, 18)], 
	options = list(
  pageLength = 17, autoWidth = TRUE
)
	)

```

Nur bei der ID 110 stand was bei Bemerkungen.

*" vergraben unter Totholz "*

Das hilft nicht wirklich weiter.
