---
title: "Abstract DPST"
author: "Johannes Osewold"
date: "03.07.2023"
output: html_document
---

```{r setup, include=FALSE}
source(file = "SCRIPT/IBF/AGGREGATED TABLES NV.R", local = knitr::knit_global())
# Das lokal ist aus irgendwelche Gründen nötig, dann tut aber die Konsole rechts
# nicht mehr.
```

## RESULTS


### TABLE NV PRO FLAECHE

```{r FLAECHEN INFOS, echo=F, warning=F, message=FALSE}


```



### TABLE ETS VERTEILUNG

Diese Tabelle erscheint als zweites im Results Teil und geht ein bisschen mehr bezüglich der ETS Sachen  ein bisschen mehr ins Detail.
```{r, echo=F, warning=F, message=FALSE}
tmp <- data_nv %>% 
	filter(Baumart_kurz == "GEs")
# str(tmp)
# 
# table(tmp$ETS.abgestorben.frisch)

# data_nv %>% 
# 	filter(Baumart_kurz == "GEs") %>% 
# 	nrow()
n_ash <- data_nv %>% 
	filter(Baumart_kurz == "GEs") %>% 
	nrow()
n_ets_gesamt <-  tmp %>% 
	filter(ETS == T) %>% 
	nrow()
n_ets_alt <-  tmp %>% 
	filter(!is.na(ETS.abgestorben.alt)) %>% 
	nrow()
n_ets_neu <- tmp %>% 
	filter(!is.na(ETS.abgestorben.frisch)) %>% 
	nrow()
n_ets_lebend <- tmp %>% 
	filter(!is.na(ETS.lebend)) %>% 
	nrow()
n_sonst <- tmp %>% 
	filter(!is.na(Sonstige.Gruende.tot)) %>%
	nrow()
				 	
n_ets_gesamt_t <- tmp %>%
	filter(ETS == T) %>%
	filter(
		ETS.abgestorben.frisch.terminal |
			ETS.abgestorben.alt.terminal |
			ETS.lebend.terminal
	) %>%
	nrow()



n_ets_alt_t <- tmp %>% 
	filter(ETS.abgestorben.alt.terminal == T) %>% 
	nrow()
n_ets_neu_t <- tmp %>% 
	filter(ETS.abgestorben.frisch.terminal == T) %>% 
	nrow()
n_ets_lebend_t <- tmp %>% 
	filter(ETS.lebend.terminal == T) %>% 
	nrow()
n_sonst_t <- tmp %>% 
	filter(Sonstige.Gruende.tot.terminal == T) %>% 
	nrow()

tmp <-
	tibble(
		" " = c(
			"Eschen gesamt",
			"ETS gesamt",
			"Abgestorbener Trieb ETS",
			"Abgestorbener Trieb ETS neu",
			"ETS Nekrosen",
			"Sonstige Guende"
		),
		"Anzahl" = c(n_ash, n_ets_gesamt, n_ets_alt, n_ets_neu, n_ets_lebend, n_sonst),
		"Terminaltrieb betroffen" = c(NA, n_ets_gesamt_t, n_ets_alt_t,
																	n_ets_neu_t, n_ets_lebend_t, 
																	n_sonst_t)
	)
write.csv(tmp, file = "EXPORT/IBF/tables/abstract_ets.csv", fileEncoding = "UTF-8")
tmp

```



```{r HOEHENVERTEILUNG, echo=F, warning=F, message=FALSE}


```





